### ISSUE TITLE
Count .jade files?

### ISSUE THREAD

**Issue by houmark** [mark-hahn/line-count#11]
Would it be possible to add support for line counting on .jade files as well?

**Comment by mark-hahn** [comment]
What are the extensions for jade?

**Comment by houmark** [comment]
Normally .jade :) See more here: http://jade-lang.com/

Also I would love to see that specific folders could be excluded by comma separation in config, so `build` and `release` folders could be excluded. And of course specific extensions as well, which I think was already suggested.

Thanks for your work and fast response :)

**Comment by mark-hahn** [comment]
Jade added in 0.3.6.

You can add the other issues as feature requests but I doubt I'll be getting to them anytime soon.  Feel free to give me a pull request.  The code is tiny and simple.

**Comment by houmark** [comment]
Thanks, I have yet to do my first code for an Atom package, but I might give it a spin :) There should be plenty of other packages out there using folders for exclusion so it shouldn't be a big deal. Even hardcoding the release and build folders would not be too big of a deal as I doubt anyone would want to count that type of code.

**Comment by houmark** [comment]
@mark-hahn I just updated, and restarted Atom and ran line-count and got the following error many times as the first output in the count results:

```
Warning: File extension 'jade' is not supported
```

What could be missing?

**Comment by mark-hahn** [comment]
I added "jade" to my list, but unfortunately the node module "sloc" (
https://www.npmjs.com/package/sloc) which I use for parsing the file
doesn't support jade.  Someone who knows jade syntax will have to submit a
formatter to the sloc project in order for it to be supported.  You might
take a look at how the formatters work.  It might be easy.
