### ISSUE TITLE
Ignore files and directories in .gitignore and core.ignoredNames setting

### ISSUE THREAD

**Issue by danielbrodin** [mark-hahn/line-count#4]
For example I don't want my generated css and .css.map files files to be counted, just my sass files

**Comment by AlexandreKilian** [comment]
definately a +1

**Comment by mark-hahn** [comment]
Does anyone know of an easy way to parse .gitignore files?

**Comment by mark-hahn** [comment]
0.4.0 now respects .gitignore.  

I don't know what the `core.ignoredNames` file is or where to find it.  If anyone cares add a new issue for it.
